# Generated by Django 5.2.7 on 2025-11-11 13:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('planilha', '0017_ilustracao_credito_alter_ilustracao_componente_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PreferenciasPreFiltro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modificado_em', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('volume', models.PositiveIntegerField(blank=True, null=True, verbose_name='Volume')),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizados', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
                ('componentes', models.ManyToManyField(blank=True, related_name='%(class)s_componentes_preferidos', to='planilha.componente', verbose_name='Componentes preferidos')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('projetos', models.ManyToManyField(blank=True, related_name='%(class)s_projetos_preferidos', to='planilha.projeto', verbose_name='Projetos preferidos')),
            ],
            options={
                'verbose_name': 'Preferência de Pré-Filtro',
                'verbose_name_plural': 'Preferências de Pré-Filtro',
                'ordering': ['id'],
            },
        ),
    ]
