# Generated by Django 5.2.7 on 2025-11-11 19:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planilha', '0018_alter_ilustracao_categoria_and_more'),
        ('usuario', '0002_preferenciasprefiltro_usuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferenciasprefiltro',
            name='volume',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Volume preferido'),
        ),
        migrations.CreateModel(
            name='PreenchimentoAutomaticoDeCampos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modificado_em', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('volume', models.PositiveIntegerField(blank=True, null=True, verbose_name='Volume preferido')),
                ('unidade', models.PositiveIntegerField(blank=True, null=True, verbose_name='Unidade preferida')),
                ('capitulo_secao', models.CharField(blank=True, null=True, verbose_name='Capítulo ou seção preferida')),
                ('lote', models.PositiveIntegerField(blank=True, null=True, verbose_name='Lote preferido')),
                ('status', models.CharField(choices=[('EDICAO_EQUIPE', 'EDICAO_EQUIPE'), ('EDICAO_ARTE', 'EDICAO_ARTE'), ('ILUSTRANDO', 'ILUSTRANDO'), ('AVALIANDO', 'AVALIANDO'), ('AJUSTANDO', 'AJUSTANDO'), ('FINALIZANDO', 'FINALIZANDO'), ('PRONTA', 'PRONTA'), ('APLICADA', 'APLICADA'), ('EXCLUÍDA', 'EXCLUÍDA')], max_length=50, verbose_name='Status')),
                ('categoria', models.CharField(choices=[('ILUSTRAÇÃO', 'ILUSTRAÇÃO'), ('IL + FOTO', 'IL + FOTO'), ('GRÁFICO', 'GRÁFICO'), ('GRÁFICO TÉC', 'GRÁFICO TÉC'), ('MAPA', 'MAPA'), ('LINHA TEMPO', 'LINHA TEMPO'), ('INFOGRÁFICO', 'INFOGRÁFICO'), ('IL TÉC ARTE', 'IL TÉC ARTE'), ('IL TÉC PADRÃO', 'IL TÉC PADRÃO'), ('IL TÉC MAT', 'IL TÉC MAT')], max_length=50, verbose_name='Categoria')),
                ('localizacao', models.CharField(choices=[('MIOLO', 'MIOLO'), ('CAPA', 'CAPA'), ('APRESENT', 'APRESENT'), ('SUMÁRIO', 'SUMÁRIO'), ('ABERTURA', 'ABERTURA'), ('PÁG ESPECIAL', 'PAG ESPECIAL'), ('MP-G', 'MP-G'), ('MP-E', 'MP-E')], max_length=50, verbose_name='Localização')),
                ('tipo', models.CharField(choices=[('AJUSTE', 'AJUSTE'), ('NOVA', 'NOVA'), ('RESGATE', 'RESGATE')], max_length=50, verbose_name='Tipo')),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizados', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
                ('componente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_componente_preferido', to='planilha.componente', verbose_name='Componente preferido')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('projeto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_projeto_preferido', to='planilha.projeto', verbose_name='Projeto preferido')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preenchimento_automatico', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Preferência de Pré-Filtro',
                'verbose_name_plural': 'Preferências de Pré-Filtro',
                'ordering': ['id'],
            },
        ),
    ]
