# Generated by Django 5.2.7 on 2025-11-11 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_alter_preferenciasprefiltro_volume_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preenchimentoautomaticodecampos',
            name='categoria',
            field=models.CharField(blank=True, choices=[('ILUSTRAÇÃO', 'ILUSTRAÇÃO'), ('IL + FOTO', 'IL + FOTO'), ('GRÁFICO', 'GRÁFICO'), ('GRÁFICO TÉC', 'GRÁFICO TÉC'), ('MAPA', 'MAPA'), ('LINHA TEMPO', 'LINHA TEMPO'), ('INFOGRÁFICO', 'INFOGRÁFICO'), ('IL TÉC ARTE', 'IL TÉC ARTE'), ('IL TÉC PADRÃO', 'IL TÉC PADRÃO'), ('IL TÉC MAT', 'IL TÉC MAT')], max_length=50, null=True, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='preenchimentoautomaticodecampos',
            name='localizacao',
            field=models.CharField(blank=True, choices=[('MIOLO', 'MIOLO'), ('CAPA', 'CAPA'), ('APRESENT', 'APRESENT'), ('SUMÁRIO', 'SUMÁRIO'), ('ABERTURA', 'ABERTURA'), ('PÁG ESPECIAL', 'PAG ESPECIAL'), ('MP-G', 'MP-G'), ('MP-E', 'MP-E')], max_length=50, null=True, verbose_name='Localização'),
        ),
        migrations.AlterField(
            model_name='preenchimentoautomaticodecampos',
            name='status',
            field=models.CharField(blank=True, choices=[('EDICAO_EQUIPE', 'EDICAO_EQUIPE'), ('EDICAO_ARTE', 'EDICAO_ARTE'), ('ILUSTRANDO', 'ILUSTRANDO'), ('AVALIANDO', 'AVALIANDO'), ('AJUSTANDO', 'AJUSTANDO'), ('FINALIZANDO', 'FINALIZANDO'), ('PRONTA', 'PRONTA'), ('APLICADA', 'APLICADA'), ('EXCLUÍDA', 'EXCLUÍDA')], max_length=50, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='preenchimentoautomaticodecampos',
            name='tipo',
            field=models.CharField(blank=True, choices=[('AJUSTE', 'AJUSTE'), ('NOVA', 'NOVA'), ('RESGATE', 'RESGATE')], max_length=50, null=True, verbose_name='Tipo'),
        ),
    ]
