# Generated by Django 5.2.7 on 2025-12-06 14:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_alter_preenchimentoautomaticodecampos_categoria_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PreferenciasColunasTabela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modificado_em', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('exibir_status', models.BooleanField(default=True, verbose_name='Status')),
                ('exibir_categoria', models.BooleanField(default=True, verbose_name='Categoria')),
                ('exibir_localizacao', models.BooleanField(default=True, verbose_name='Localização')),
                ('exibir_volume', models.BooleanField(default=True, verbose_name='Volume')),
                ('exibir_unidade', models.BooleanField(default=True, verbose_name='Unidade')),
                ('exibir_capitulo_secao', models.BooleanField(default=True, verbose_name='Capítulo/Seção')),
                ('exibir_pagina', models.BooleanField(default=True, verbose_name='Página')),
                ('exibir_tipo', models.BooleanField(default=True, verbose_name='Tipo')),
                ('exibir_descricao', models.BooleanField(default=True, verbose_name='Descrição')),
                ('exibir_observacao_edit_nuc', models.BooleanField(default=True, verbose_name='Observação editorial e núcleo')),
                ('exibir_lote', models.BooleanField(default=True, verbose_name='Lote')),
                ('exibir_data_liberacao_para_arte', models.BooleanField(default=True, verbose_name='Data de liberação para arte')),
                ('exibir_data_envio_pedido', models.BooleanField(default=True, verbose_name='Data de envio do pedido')),
                ('exibir_data_recebimento_rafe', models.BooleanField(default=True, verbose_name='Data de recebimento do rafe')),
                ('exibir_data_retorno_rafe', models.BooleanField(default=True, verbose_name='Data de retorno do rafe')),
                ('exibir_data_recebimento_finalizada', models.BooleanField(default=True, verbose_name='Data de recebimento da finalizada')),
                ('exibir_classificacao', models.BooleanField(default=True, verbose_name='Classificação')),
                ('exibir_credito', models.BooleanField(default=True, verbose_name='Crédito')),
                ('exibir_ilustrador_resgate', models.BooleanField(default=True, verbose_name='Ilustrador resgate')),
                ('exibir_ilustrador', models.BooleanField(default=True, verbose_name='Ilustrador criação')),
                ('exibir_ilustrador_ajuste', models.BooleanField(default=True, verbose_name='Ilustrador ajuste')),
                ('exibir_observacao_arte', models.BooleanField(default=False, verbose_name='Observação da arte')),
                ('exibir_pagamento', models.BooleanField(default=True, verbose_name='Pagamento')),
                ('exibir_modificado_em', models.BooleanField(default=True, verbose_name='Modificada')),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizados', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferencias_colunas', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Preferência de colunas da tabela',
                'verbose_name_plural': 'Preferências de colunas da tabela',
                'ordering': ['id'],
            },
        ),
    ]
