# Generated by Django 5.2.7 on 2025-12-08 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0005_preferenciascolunastabela'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferenciascolunastabela',
            name='exibir_componente',
            field=models.BooleanField(default=True, verbose_name='Componente'),
        ),
        migrations.AddField(
            model_name='preferenciascolunastabela',
            name='exibir_projeto',
            field=models.BooleanField(default=True, verbose_name='Projeto'),
        ),
        migrations.AlterField(
            model_name='preferenciascolunastabela',
            name='exibir_observacao_arte',
            field=models.BooleanField(default=True, verbose_name='Observação da arte'),
        ),
    ]
