# Generated by Django 5.2.7 on 2025-12-09 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0006_preferenciascolunastabela_exibir_componente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferenciascolunastabela',
            name='exibir_atualizado_por',
            field=models.BooleanField(default=True, verbose_name='Modificado por'),
        ),
        migrations.AddField(
            model_name='preferenciascolunastabela',
            name='exibir_criado_em',
            field=models.BooleanField(default=True, verbose_name='Criado em'),
        ),
        migrations.AddField(
            model_name='preferenciascolunastabela',
            name='exibir_criado_por',
            field=models.BooleanField(default=True, verbose_name='Criado por'),
        ),
        migrations.AlterField(
            model_name='preferenciascolunastabela',
            name='exibir_modificado_em',
            field=models.BooleanField(default=True, verbose_name='Modificado em'),
        ),
    ]
