# Generated by Django 5.2.7 on 2026-02-02 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0007_preferenciascolunastabela_exibir_atualizado_por_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preenchimentoautomaticodecampos',
            name='localizacao',
            field=models.CharField(blank=True, choices=[('MIOLO', 'MIOLO'), ('CAPA', 'CAPA'), ('APRESENT', 'APRESENT'), ('SUMÁRIO', 'SUMÁRIO'), ('ABERTURA', 'ABERTURA'), ('PÁG ESPECIAL', 'PAG ESPECIAL'), ('MP-G', 'MP-G'), ('MP-E', 'MP-E'), ('OED', 'OED')], max_length=50, null=True, verbose_name='Localização'),
        ),
    ]
