# Generated by Django 5.2.7 on 2026-02-02 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0008_alter_preenchimentoautomaticodecampos_localizacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preferenciascolunastabela',
            name='exibir_ilustrador_resgate',
        ),
    ]
