# Generated by Django 5.2.7 on 2026-02-02 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0009_remove_preferenciascolunastabela_exibir_ilustrador_resgate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferenciascolunastabela',
            name='exibir_lote',
            field=models.BooleanField(default=False, verbose_name='Lote'),
        ),
    ]
