# Generated by Django 5.2.7 on 2026-02-09 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0010_alter_preferenciascolunastabela_exibir_lote'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoIlustracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(choices=[('AJUSTE', 'AJUSTE'), ('NOVA', 'NOVA'), ('RESGATE', 'RESGATE')], max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo de Ilustração',
                'verbose_name_plural': 'Tipos de Ilustração',
            },
        ),
        migrations.AddField(
            model_name='preferenciasprefiltro',
            name='tipos',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_tipos_preferidos', to='usuario.tipoilustracao', verbose_name='Tipos preferidos'),
        ),
    ]
