# Generated by Django 5.2.7 on 2026-03-11 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0011_tipoilustracao_preferenciasprefiltro_tipos'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferenciasprefiltro',
            name='registros_por_pagina',
            field=models.PositiveIntegerField(default=100, verbose_name='Número de ilustras por página'),
        ),
    ]
