# Generated by Django 5.2.7 on 2026-04-01 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0012_preferenciasprefiltro_registros_por_pagina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferenciasprefiltro',
            name='registros_por_pagina',
            field=models.PositiveIntegerField(default=100, verbose_name='Número de ilustrações por página'),
        ),
    ]
