# Generated by Django 5.2.7 on 2026-04-02 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0013_alter_preferenciasprefiltro_registros_por_pagina'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferenciasprefiltro',
            name='abrir_ilustracaoupdateview_em_nova_aba',
            field=models.BooleanField(default=True, verbose_name='Abrir detalhe da ilustração em nova aba'),
        ),
    ]
