# Generated by Django 5.2.7 on 2025-11-04 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('editora', models.CharField(max_length=100)),
                ('ciclo', models.CharField(max_length=100)),
            ],
        ),
    ]
