# Generated by Django 5.2.7 on 2025-11-04 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planilha', '0002_componente'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='arquivado',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
