# Generated by Django 5.2.7 on 2025-11-05 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planilha', '0004_delete_componente_projeto_ativo_projeto_criado_em_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projeto',
            name='arquivado',
        ),
    ]
