# Generated by Django 5.2.7 on 2025-11-06 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planilha', '0005_remove_projeto_arquivado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ilustracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modificado_em', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('retranca', models.CharField(max_length=100, verbose_name='Retranca')),
                ('descricao', models.CharField(max_length=100, verbose_name='Descrição')),
                ('volume', models.IntegerField(verbose_name='Volume')),
                ('status', models.CharField(choices=[('ILUSTRANDO', 'ILUSTRANDO'), ('PRONTA', 'PRONTA'), ('AJUSTANDO', 'AJUSTANDO')], default='ILUSTRANDO', max_length=50, verbose_name='Status')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
