# Generated by Django 5.2.7 on 2025-11-07 12:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planilha', '0008_componente_atualizado_por_componente_criado_por_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='componente',
            options={'ordering': ['nome']},
        ),
        migrations.AlterModelOptions(
            name='ilustracao',
            options={'ordering': ['retranca']},
        ),
        migrations.AlterModelOptions(
            name='projeto',
            options={'ordering': ['nome']},
        ),
        migrations.AddField(
            model_name='ilustracao',
            name='capitulo_secao',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Capítulo ou seção'),
        ),
        migrations.AddField(
            model_name='ilustracao',
            name='categoria',
            field=models.CharField(choices=[('ILUSTRAÇÃO', 'ILUSTRAÇÃO'), ('IL + FOTO', 'IL + FOTO'), ('GRÁFICO', 'GRÁFICO'), ('GRÁFICO TÉC', 'GRÁFICO TÉC'), ('MAPA', 'MAPA'), ('LINHA TEMPO', 'LINHA TEMPO'), ('INFOGRÁFICO', 'INFOGRÁFICO'), ('IL TÉC ARTE', 'IL TÉC ARTE'), ('IL TÉC PADRÃO', 'IL TÉC PADRÃO'), ('IL TÉC MAT', 'IL TÉC MAT')], default='ILUSTRAÇÃO', max_length=50, verbose_name='Categoria'),
        ),
        migrations.AddField(
            model_name='ilustracao',
            name='localizacao',
            field=models.CharField(choices=[('MIOLO', 'MIOLO'), ('CAPA', 'CAPA'), ('APRESENT', 'APRESENT'), ('SUMÁRIO', 'SUMÁRIO'), ('ABERTURA', 'ABERTURA'), ('PÁG ESPECIAL', 'PAG ESPECIAL'), ('MP-G', 'MP-G'), ('MP-E', 'MP-E')], default='MIOLO', max_length=50, verbose_name='Localização'),
        ),
        migrations.AddField(
            model_name='ilustracao',
            name='pagina',
            field=models.IntegerField(blank=True, null=True, verbose_name='Página'),
        ),
        migrations.AddField(
            model_name='ilustracao',
            name='tipo',
            field=models.CharField(choices=[('AJUSTE', 'AJUSTE'), ('NOVA', 'NOVA'), ('RESGATE', 'RESGATE')], default='NOVA', max_length=50, verbose_name='Tipo'),
        ),
        migrations.AddField(
            model_name='ilustracao',
            name='unidade',
            field=models.IntegerField(blank=True, null=True, verbose_name='Unidade'),
        ),
        migrations.AlterField(
            model_name='componente',
            name='nome',
            field=models.CharField(max_length=100, unique=True, verbose_name='Componente'),
        ),
        migrations.AlterField(
            model_name='ilustracao',
            name='retranca',
            field=models.CharField(max_length=100, unique=True, verbose_name='Retranca'),
        ),
        migrations.AlterField(
            model_name='ilustracao',
            name='status',
            field=models.CharField(choices=[('EDICAO_EQUIPE', 'EDICAO_EQUIPE'), ('EDICAO_ARTE', 'EDICAO_ARTE'), ('ILUSTRANDO', 'ILUSTRANDO'), ('AVALIANDO', 'AVALIANDO'), ('AJUSTANDO', 'AJUSTANDO'), ('FINALIZANDO', 'FINALIZANDO'), ('PRONTA', 'PRONTA'), ('APLICADA', 'APLICADA'), ('EXCLUÍDA', 'EXCLUÍDA')], default='EDICAO_EQUIPE', max_length=50, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='ilustracao',
            name='volume',
            field=models.IntegerField(blank=True, null=True, verbose_name='Volume'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='nome',
            field=models.CharField(max_length=100, unique=True, verbose_name='Projeto'),
        ),
        migrations.CreateModel(
            name='Ilustrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modificado_em', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('nome', models.CharField(max_length=150, unique=True, verbose_name='Nome do ilustrador')),
                ('contato', models.EmailField(blank=True, max_length=150, null=True, verbose_name='E-mail de contato')),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizados', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Ilustrador',
                'verbose_name_plural': 'Ilustradores',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='ilustracao',
            name='ilustrador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ilustracoes_associadas', to='planilha.ilustrador', verbose_name='Ilustrador'),
        ),
    ]
