# Generated by Django 5.2.7 on 2025-11-07 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planilha', '0009_alter_componente_options_alter_ilustracao_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ilustracao',
            name='classificacao',
            field=models.IntegerField(blank=True, null=True, verbose_name='Classificação'),
        ),
        migrations.AddField(
            model_name='ilustracao',
            name='credito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creditos_associados', to='planilha.ilustrador', verbose_name='Crédito'),
        ),
        migrations.AddField(
            model_name='ilustracao',
            name='data_envio_pedido',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de envio do pedido'),
        ),
        migrations.AddField(
            model_name='ilustracao',
            name='data_liberacao_para_arte',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de liberação do lote'),
        ),
        migrations.AddField(
            model_name='ilustracao',
            name='data_recebimento_finalizada',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de recebimento da finalizada'),
        ),
        migrations.AddField(
            model_name='ilustracao',
            name='data_recebimento_rafe',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de recebimento do rafe'),
        ),
        migrations.AddField(
            model_name='ilustracao',
            name='data_retorno_rafe',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de retorno do rafe'),
        ),
        migrations.AddField(
            model_name='ilustracao',
            name='ilustrador_ajuste',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ilustracoes_ajustadas', to='planilha.ilustrador', verbose_name='Ilustrador ajuste'),
        ),
        migrations.AddField(
            model_name='ilustracao',
            name='ilustrador_resgate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ilustracoes_resgatadas', to='planilha.ilustrador', verbose_name='Ilustrador resgate'),
        ),
        migrations.AddField(
            model_name='ilustracao',
            name='lote',
            field=models.IntegerField(blank=True, null=True, verbose_name='Lote'),
        ),
        migrations.AddField(
            model_name='ilustracao',
            name='observacao_arte',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Observação arte'),
        ),
        migrations.AddField(
            model_name='ilustracao',
            name='observacao_edit_nuc',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Observação editorial e núcleo'),
        ),
        migrations.AddField(
            model_name='ilustracao',
            name='pagamento',
            field=models.CharField(choices=[('AVALIAR', 'AVALIAR'), ('PREVISÃO', 'PREVISÃO'), ('FINALIZADO', 'FINALIZADO'), ('FINALIZADO RAFE', 'FINALIZADO RAFE'), ('PAGO', 'PAGO'), ('PAGO RAFE', 'PAGO RAFE'), ('SEM PAGAMENTO', 'SEM PAGAMENTO')], default='AVALIAR', max_length=50, verbose_name='Pagamento'),
        ),
        migrations.AddField(
            model_name='ilustrador',
            name='sigla',
            field=models.CharField(default='aa', max_length=20, unique=True, verbose_name='Sigla do ilustrador'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ilustracao',
            name='ilustrador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ilustracoes_criadas', to='planilha.ilustrador', verbose_name='Ilustrador criação'),
        ),
    ]
