# Generated by Django 5.2.7 on 2025-11-07 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planilha', '0010_ilustracao_classificacao_ilustracao_credito_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ilustracao',
            name='descricao',
            field=models.TextField(max_length=2000, verbose_name='Descrição'),
        ),
    ]
