# Generated by Django 5.2.7 on 2025-11-07 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planilha', '0011_alter_ilustracao_descricao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ilustrador',
            old_name='contato',
            new_name='email',
        ),
        migrations.AddField(
            model_name='ilustrador',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone do contato'),
        ),
    ]
