# Generated by Django 5.2.7 on 2025-11-08 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planilha', '0012_rename_contato_ilustrador_email_ilustrador_telefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='ilustrador',
            name='credito',
            field=models.CharField(default='preencher', max_length=150, verbose_name='Crédito do ilustrador'),
            preserve_default=False,
        ),
    ]
