# Generated by Django 5.2.7 on 2025-11-09 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planilha', '0013_ilustrador_credito'),
    ]

    operations = [
        migrations.AddField(
            model_name='ilustracao',
            name='componente',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.PROTECT, related_name='componentes_associados', to='planilha.componente', verbose_name='Componente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ilustracao',
            name='projeto',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.PROTECT, related_name='projetos_associados', to='planilha.projeto', verbose_name='Projeto'),
            preserve_default=False,
        ),
    ]
