# Generated by Django 5.2.7 on 2025-11-09 20:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planilha', '0014_ilustracao_componente_ilustracao_projeto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ilustracao',
            name='credito',
        ),
        migrations.RemoveField(
            model_name='ilustrador',
            name='credito',
        ),
        migrations.CreateModel(
            name='Credito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modificado_em', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Crédito')),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizados', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('projetos', models.ManyToManyField(related_name='creditos_associados', to='planilha.projeto', verbose_name='Projetos associados')),
            ],
            options={
                'verbose_name': 'Crédito',
                'verbose_name_plural': 'Créditos',
                'ordering': ['nome'],
            },
        ),
    ]
