# Generated by Django 5.2.7 on 2025-11-10 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planilha', '0015_remove_ilustracao_credito_remove_ilustrador_credito_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='credito',
            name='componentes',
            field=models.ManyToManyField(blank=True, null=True, related_name='creditos_componentes_associados', to='planilha.componente', verbose_name='Componentes associados'),
        ),
        migrations.AlterField(
            model_name='credito',
            name='projetos',
            field=models.ManyToManyField(blank=True, null=True, related_name='creditos_projetos_associados', to='planilha.projeto', verbose_name='Projetos associados'),
        ),
    ]
