# Generated by Django 5.2.7 on 2025-11-10 00:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planilha', '0016_credito_componentes_alter_credito_projetos'),
    ]

    operations = [
        migrations.AddField(
            model_name='ilustracao',
            name='credito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ilustracoes_creditos_associados', to='planilha.credito', verbose_name='Crédito'),
        ),
        migrations.AlterField(
            model_name='ilustracao',
            name='componente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ilustracoes_componentes_associados', to='planilha.componente', verbose_name='Componente'),
        ),
        migrations.AlterField(
            model_name='ilustracao',
            name='projeto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ilustracoes_projetos_associados', to='planilha.projeto', verbose_name='Projeto'),
        ),
    ]
