# Generated by Django 5.2.7 on 2025-11-11 19:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planilha', '0017_ilustracao_credito_alter_ilustracao_componente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ilustracao',
            name='categoria',
            field=models.CharField(choices=[('ILUSTRAÇÃO', 'ILUSTRAÇÃO'), ('IL + FOTO', 'IL + FOTO'), ('GRÁFICO', 'GRÁFICO'), ('GRÁFICO TÉC', 'GRÁFICO TÉC'), ('MAPA', 'MAPA'), ('LINHA TEMPO', 'LINHA TEMPO'), ('INFOGRÁFICO', 'INFOGRÁFICO'), ('IL TÉC ARTE', 'IL TÉC ARTE'), ('IL TÉC PADRÃO', 'IL TÉC PADRÃO'), ('IL TÉC MAT', 'IL TÉC MAT')], max_length=50, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='ilustracao',
            name='classificacao',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Classificação'),
        ),
        migrations.AlterField(
            model_name='ilustracao',
            name='data_liberacao_para_arte',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Data de liberação do lote'),
        ),
        migrations.AlterField(
            model_name='ilustracao',
            name='localizacao',
            field=models.CharField(choices=[('MIOLO', 'MIOLO'), ('CAPA', 'CAPA'), ('APRESENT', 'APRESENT'), ('SUMÁRIO', 'SUMÁRIO'), ('ABERTURA', 'ABERTURA'), ('PÁG ESPECIAL', 'PAG ESPECIAL'), ('MP-G', 'MP-G'), ('MP-E', 'MP-E')], max_length=50, verbose_name='Localização'),
        ),
        migrations.AlterField(
            model_name='ilustracao',
            name='lote',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Lote'),
        ),
        migrations.AlterField(
            model_name='ilustracao',
            name='pagina',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Página'),
        ),
        migrations.AlterField(
            model_name='ilustracao',
            name='status',
            field=models.CharField(choices=[('EDICAO_EQUIPE', 'EDICAO_EQUIPE'), ('EDICAO_ARTE', 'EDICAO_ARTE'), ('ILUSTRANDO', 'ILUSTRANDO'), ('AVALIANDO', 'AVALIANDO'), ('AJUSTANDO', 'AJUSTANDO'), ('FINALIZANDO', 'FINALIZANDO'), ('PRONTA', 'PRONTA'), ('APLICADA', 'APLICADA'), ('EXCLUÍDA', 'EXCLUÍDA')], max_length=50, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='ilustracao',
            name='tipo',
            field=models.CharField(choices=[('AJUSTE', 'AJUSTE'), ('NOVA', 'NOVA'), ('RESGATE', 'RESGATE')], max_length=50, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='ilustracao',
            name='unidade',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Unidade'),
        ),
        migrations.AlterField(
            model_name='ilustracao',
            name='volume',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Volume'),
        ),
    ]
