# Generated by Django 5.2.7 on 2025-11-11 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planilha', '0018_alter_ilustracao_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ilustracao',
            name='volume',
            field=models.PositiveIntegerField(default=0, verbose_name='Volume'),
            preserve_default=False,
        ),
    ]
