# Generated by Django 5.2.7 on 2026-02-02 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planilha', '0019_alter_ilustracao_volume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credito',
            name='componentes',
            field=models.ManyToManyField(blank=True, related_name='creditos_componentes_associados', to='planilha.componente', verbose_name='Componentes associados'),
        ),
        migrations.AlterField(
            model_name='credito',
            name='projetos',
            field=models.ManyToManyField(blank=True, related_name='creditos_projetos_associados', to='planilha.projeto', verbose_name='Projetos associados'),
        ),
        migrations.AlterField(
            model_name='ilustracao',
            name='localizacao',
            field=models.CharField(choices=[('MIOLO', 'MIOLO'), ('CAPA', 'CAPA'), ('APRESENT', 'APRESENT'), ('SUMÁRIO', 'SUMÁRIO'), ('ABERTURA', 'ABERTURA'), ('PÁG ESPECIAL', 'PAG ESPECIAL'), ('MP-G', 'MP-G'), ('MP-E', 'MP-E'), ('OED', 'OED')], max_length=50, verbose_name='Localização'),
        ),
    ]
