# Generated by Django 5.2.7 on 2026-02-02 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planilha', '0020_alter_credito_componentes_alter_credito_projetos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ilustracao',
            name='ilustrador_resgate',
        ),
    ]
