# Generated by Django 5.2.7 on 2026-02-02 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planilha', '0021_remove_ilustracao_ilustrador_resgate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ilustracao',
            name='lote',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Lote'),
        ),
    ]
