# Generated by Django 5.2.7 on 2026-02-08 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planilha', '0022_alter_ilustracao_lote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ilustracao',
            name='observacao_arte',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Observação da arte'),
        ),
    ]
