# Generated by Django 5.2.7 on 2026-04-01 20:19

from django.db import migrations

def forwards(apps, schema_editor):
    Ilustracao = apps.get_model('planilha', 'Ilustracao')

    # 🔁 Mapeamento antigo → novo

    Ilustracao.objects.filter(pagamento='PREVISÃO').update(pagamento='AVALIAR')

    Ilustracao.objects.filter(pagamento='FINALIZADO').update(pagamento='AVALIAR')

    Ilustracao.objects.filter(pagamento='FINALIZADO RAFE').update(
        pagamento='PAGAR_FINALIZACAO_DO_RAFE'
    )
    Ilustracao.objects.filter(pagamento='PAGO').update(pagamento='PAGO_INTEGRAL_OK')

    Ilustracao.objects.filter(pagamento='PAGO RAFE').update(
        pagamento='PAGO_RAFE_OK'
    )
    Ilustracao.objects.filter(pagamento='SEM PAGAMENTO').update(
        pagamento='SEM_PAGAMENTO'
    )
    


class Migration(migrations.Migration):

    dependencies = [
        ('planilha', '0023_alter_ilustracao_observacao_arte'),
    ]

    operations = [
        migrations.RunPython(forwards),
    ]
