# Generated by Django 5.2.7 on 2026-04-01 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planilha', '0024_migrate_pagamento_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ilustracao',
            name='pagamento',
            field=models.CharField(choices=[('AVALIAR', 'AVALIAR'), ('SEM_PAGAMENTO', 'SEM PAGAMENTO'), ('PAGAR_RAFE', 'Pagar RAFE'), ('PAGO_RAFE_OK', 'PAGO RAFE OK'), ('PAGAR_INTEGRAL', 'Pagar INTEGRAL'), ('PAGO_INTEGRAL_OK', 'PAGO INTEGRAL OK'), ('PAGAR_FINALIZACAO_DO_RAFE', 'Pagar FINALIZAÇÃO DO RAFE'), ('PAGO_FINALIZACAO_DO_RAFE_OK', 'Pago FINALIZAÇÃO DO RAFE OK')], default='AVALIAR', max_length=50, verbose_name='Pagamento'),
        ),
    ]
