# Generated by Django 5.2.7 on 2026-09-08 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planilha', '0025_alter_ilustracao_pagamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ilustracao',
            name='descricao',
            field=models.TextField(max_length=4000, verbose_name='Descrição'),
        ),
    ]
